export const enum DefaultLoggerMessage {
  GuildIsNotDefined = 'Guild is not defined.',
  GuildNotAvailableInteraction = 'Guild not available in this interaction.',
  NoClientToken = 'Unable to start this discord bot. There is no Discord client token. Check if the environment specifies the CLIENT_TOKEN value.',
  NoExtractorsRegistered = 'No extractors registered. Unable to use this discord bot.',
  UnableToFindChannelToControl = 'Unable to find channel to control.',
  UnableToRetrieveCurrentQueueTimestamp = 'Unable to retrieve the current queue`s timestamp.',
  SomethingWentWrongTryingToFindTrack = 'Something went wrong when trying to find the track.',
  UnableToFindSlashCommand = 'Unable to find slash command with name - ',
  UnableToHandleCommand = 'An error occurred trying to handle the command. Error: ',
  InternalServerError = 'An internal server error occurred. Unable to handle request.',
  LocaleInstanceNotAvailable = 'Failed to retrieve localization value. The global localization instance is not available.',
  CouldNotFindMainFile = 'Could not find a main file.',
  NoButtonsForMessage = 'There are no buttons for this message.',
  CouldNotFindCommand = 'Could not find this command.',
  PlayerNodeInitialization = 'Player node initialization.',
  PlayerNodeDestroyed = 'Player node destroyed.',
  PlayerNodeSkip = 'Player node skip.',
  PlayerNodeConnection = 'Player node connection.',
  PlayerTrackStart = 'Player track start.',
  PlayerTrackAdd = 'Player track add.',
  PlayerTrackAddEnd = 'Player track add end.',
  PlayerNoResults = 'Player no results.',
  PlayerError = 'Player error.',
  MusicFolderPathNotSet = 'MUSIC_FOLDER_PATH environment variable is not set.',
  ErrorReadingMusicFolder = 'Error reading music folder.',
}
